spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    ?serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://database.cbrxpiqol1fu.ap-northeast-2.rds.amazonaws.com:3306/blog
    username: qtwe153
    password: sonamu0928*

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    # show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
